container:
  activeProfile: "dev"
  replicas: 1

image:
  tag: develop

service:
  internal: true
  annotations: {}

ingress:
  hosts:
    - host: dev-springboot.comstering.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  annotations: {}

resources:
  limits:
    cpu: 0.5
    memory: 1024Mi

  requests:
    cpu: 0.1
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
