container:
  activeProfile: "production"
  replicas: 1

image:
  tag: main

service:
  internal: true
  annotations: {}

ingress:
  hosts:
    - host: springboot.comstering.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  annotations: {}

resources:
  limits:
    cpu: 2.0
    memory: 1024Mi

  requests:
    cpu: 0.1
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
