apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-server.fullname" . }}
  labels:
    {{- include "springboot-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
  selector:
    {{- include "springboot-server.selectorLabels" . | nindent 4 }}
