name: Feature Test

on:
  push:
    branches: [ feature/** ]

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      # 현재 코드 레포지토리 업로드
      - name: Checkout my code
        uses: actions/checkout@v3

      # Java jdk 설치
      - name: Set up jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Coveralls repo token 등록
      - name: Set coveralls repo token in environment
        run: echo "COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}" >> $GITHUB_ENV

      # 테스트 & Coverage 측정
      - name: Run test
        run: |
          ./gradlew test
          ./gradlew coveralls
