name: Staging Deploy

on:
  push:
    branches: [ release/**, hotfix/** ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      # 현재 코드 레포지토리 업로드
      - name: Checkout my code
        uses: actions/checkout@v3

      # Java jdk 설치
      - name: Set up jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 테스트
      - name: Run test
        run: ./gradlew test

      # Coveralls repo token 등록
      - name: Set coveralls repo token in environment
        run: echo "COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}" >> $GITHUB_ENV

      # Coverage 측정 (use coveralls)
      - name: Run Coverage measurement (use coveralls)
        run: ./gradlew coveralls


  build:
    name: JIB Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      # 현재 코드 레포지토리 업로드
      - name: Checkout my code
        uses: actions/checkout@v3

      # Docker Hub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Java jdk 설치
      - name: Set up jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # JIB Build
      - name: JIB Build
        run: |
          ./gradlew application:jib

  deploy:
    # Todo: I write deploy script after
    name: Deploy staging
    runs-on: ubuntu-latest
    needs: build
    environment: staging

    steps:
      - name: Deploy to preview
        run: |
          echo '${{ github.sha }}'
